[package]
name = "squishy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "1.1.1"
indicatif = "0.17.7"
noodles = { version = "0.60.0", features = ["core", "bam", "sam"] }
